{% set version = "2.0-10" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-extremes
  version: {{ version|replace("-", "_") }}

source:
  fn: extRemes_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/extRemes_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/extRemes/extRemes_{{ version }}.tar.gz
  sha256: 2c96ae999b0a64f38e5f39e6e913009f18aa1e7f6cd4054b32a6097c9f38d221

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base
    - r-lmoments
    - r-car
    - r-distillery

  run:
    - r-base
    - r-lmoments
    - r-car
    - r-distillery

test:
  commands:
    - $R -e "library('extRemes')"  # [not win]
    - "\"%R%\" -e \"library('extRemes')\""  # [win]

about:
  home: http://www.assessment.ucar.edu/toolkit/
  license: GPL (>= 2)
  summary: Functions for performing extreme value analysis.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - dpryan79
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
