appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: j10CNhtBbRPkNCvO1LObz43z+pvKFDx1Nq9EfoHRc5BitCCepD6RAWyVSK7gkghbRt/SvcPjXFeEozhKc9EG/og1A8wtkHAXPk0AAnLjG/TxyDEB/ArTJQqiyxgFcfQZa2Z7ZuPPkX0S/61Sy/8r4T2aIhbdAOSHiiX/xvShU6n7HLjSGhosLceX9kFcOWtRcyGU/QQ8dRIRHC6ToWTNkK0jTgkP3+dazeif3AAsbJ2x1kmcG9UxnOtSlWfasDsRL7NO0giHxpXPWwhfBo2I92WFAx2CRklE0BRshEEBfFUFnRCvkAHad8v3DXbulIbCbqG9EVopIAXr9neuhtyJ/zxWNSGfbYrFNo+qJaj8CXQk8RskC3iBIOps+lgxZucds3/s29dU+PfkGrT9CdpJhsnfF4LXxJIj0oCgxiPEJB7qnQl2xyCpHKtHa/ADCOIlZ2YCLodSqMy7WLyGvri1g7ToblxE0H+c4brQiIvQK12l14xsF081XM8NjJVc4lH+hOD6xncYBwj10SsrlAlFEZkv4dC80rdKtxl6A3JoxYbyTT6OI9/5nmCcbasjQ/Kr2f0t+1PyvNg/TBC0qunZ7izmG2yrAN7ziacPnPI7AgLer0vuIvD50n9fsxOc2U85SPBspgr+NfnrxPk4N/kGCMbQvfo4bORw/BVvk8QhRF8=}
bot:
  automerge: true
