travis:
  secure:
    BINSTAR_TOKEN: GAw5BF/TZ6Rv89u57hDijRqrosxfDrPYLl07mk/3W82mMbYBk/E/ElqVubo7XcXdesrV0dhdKgUTuWAlJ5fgcumolfWODsUjJ8f248Q0aFMrx4w/p0MOhNnannratdYqj0vOkAu7LmEczF/J1M2vS3Bv4AgPMsVdvGvpgKxxt17AYKnXcK7WK2EVfTTVVla5ZeC0yqw4TRD4Lho0ucXsoJhBO1CosfsdsDjrUjXlYvrEggamcOarn4ojb9TMr6DvaZhohMgnSDHsFyeYoRkN9273fRm2dC+Klhvv/WL+jB1k05v1mRtOMpdLctiRm2FrfvEXxUqcA3iVKwlV6eaQNDg2Lr9FMO7qp8tSipmzl7IBlacDtUqdMt6/H6Y9wvDoHMD/w4113Lf1V2EwrwV4OXhj6//iMDiK/inqUfEuB+uIvznjp4A0/N3VsZRZPXz89ZZysoIngmWEuaXHf97XSvM3NrG6oB8LVudtyPccGRmbo1E/cIOkqrcVoEmSBVdwqARFufgCrLdlaBUIj+SnAUYsJgVFi8paSDVhhJ1PT+3NUdZyCogFSbHqTfK3ZGH2a80s8uY+NnhuK/EkoHGK/SUMUdOQMMlUNauU+wRsKsOCHzKx0+/uC9SC0YriSQleW3lK+TBQoz2yiQq4AC6F5bvFuNcVoE/fDa8hmydsBR4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
